[package]
name = "trojan"
version = "0.8.5"
authors = ["Hoping White <baihaoping@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-rc.0", features = ["derive", "cargo", "env"]}
mio = { version = "0.8", features = ["net", "os-poll"] }
log = "0.4"
chrono = "0.4"
libc = "0.2"
rustls = "0.20"
rust-crypto = "0.2"
bytes = "1.1"
dns-lookup = "1.0"
cfg-if = "1.0"
webpki-roots = "0.22"
webpki = "0.22"
mio-extras = "2.0"
socket2 = "0.4"
rayon = "1.5"
rustls-pemfile = "0.2"
lazy_static = "1.4"
derive_more = "0.99"
clap-num = "0.2"
libloading = "0.7"
crossbeam = "0.8"
smoltcp = {git = "https://github.com/smoltcp-rs/smoltcp.git"}

[target.'cfg(windows)'.dependencies]
wintun = "0.2"

[dependencies.fern]
version = "0.6"
features = ["reopen-03"]

[profile.release]
lto = true
